apiVersion: apps/v1
kind: Deployment
metadata:
  name: citydata
spec:
  replicas: 2
  selector:
    matchLabels:
      app: citydata
  template:
    metadata:
      labels:
        app: citydata
    spec:
      containers:
      - name: citydata
        image: techchallengeregistry.azurecr.io/citydata:latest
        ports:
        - containerPort: 80
