apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: masstransit/rabbitmq
        ports:
        - containerPort: 5672
        - containerPort: 15672
        envFrom:
        - secretRef:
            name: rabbitmq-secrets
        resources: # Opcional: Defina recursos para o RabbitMQ
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
  - protocol: TCP
    port: 5672 # Porta acessível externamente
    targetPort: 5672 # Porta do container
  - protocol: TCP
    port: 15672 # Porta acessível externamente (painel de gerenciamento)
    targetPort: 15672 # Porta do container
  type: LoadBalancer # Ou ClusterIP se você não precisar de acesso externo direto