apiVersion: apps/v1
kind: Deployment
metadata:
  name: regionalproducer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: regionalproducer
  template:
    metadata:
      labels:
        app: regionalproducer
    spec:
      containers:
      - name: regionalproducer
        image: techchallengeregistry.azurecr.io/regionalproducer:latest
        ports:
        - containerPort: 80
