apiVersion: apps/v1
kind: Deployment
metadata:
  name: citydata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shared-service
  template:
    metadata:
      labels:
        app: shared-service
    spec:
      imagePullSecrets:  # <-- Deve estar aqui, não dentro do container
      - name: acr-secret 
      containers:
      - name: citydata
        image: techchallengeregistry.azurecr.io/citydata:latest
        ports:
        - containerPort: 8080
  