apiVersion: v1
kind: Service
metadata:
  name: citydata-service
spec:
  selector:
    app: citydata
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: prometheus
  type: LoadBalancer
