apiVersion: apps/v1
kind: Deployment
metadata:
  name: citydata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: citydata
  template:
    metadata:
      labels:
        app: citydata
    spec:
      imagePullSecrets: 
      - name: acr-secret 
      containers:
      - name: citydata
        image: techchallengeregistry.azurecr.io/citydata:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: citydata
spec:
  selector:  
    app: citydata
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http 
  type: ClusterIP
