apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: masstransit/rabbitmq # Usando a imagem oficial
        ports:
        - containerPort: 5672
        - containerPort: 15672
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "regional"
        - name: RABBITMQ_DEFAULT_PASS
          value: "R3gional!234"
        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq-storage
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      volumes:
      - name: rabbitmq-storage
        emptyDir: {} # Substitua por PVC se precisar de persistência real
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672
    name: amqp
  - protocol: TCP
    port: 15672
    targetPort: 15672
    name: management
  type: ClusterIP # Use LoadBalancer apenas se precisar de acesso externo
