apiVersion: apps/v1
kind: Deployment
metadata:
  name: regionaldata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: regionaldata
  template:
    metadata:
      labels:
        app: regionaldata
    spec:
      imagePullSecrets: 
      - name: acr-secret 
      containers:
      - name: regionaldata
        image: techchallengeregistry.azurecr.io/regionaldata:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: regionaldata
spec:
  selector:  
    app: regionaldata
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http 
  type: ClusterIP