apiVersion: apps/v1
kind: Deployment
metadata:
  name: regionaldata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: regionaldata
  template:
    metadata:
      labels:
        app: regionaldata
    spec:
      imagePullSecrets:  # <-- Deve estar aqui, não dentro do container
      - name: acr-secret 
      containers:
      - name: regionaldata
        image: techchallengeregistry.azurecr.io/regionaldata:latest
        ports:
        - containerPort: 80
        - containerPort: 8080
  