apiVersion: apps/v1
kind: Deployment
metadata:
  name: regionalwriter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: regionalwriter
  template:
    metadata:
      labels:
        app: regionalwriter
    spec:
      containers:
      - name: regionalwriter
        image: techchallengeregistry.azurecr.io/regionalwriter:latest
        ports:
        - containerPort: 80
