apiVersion: apps/v1
kind: Deployment
metadata:
  name: regionalproducer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: regionalproducer
  template:
    metadata:
      labels:
        app: regionalproducer
    spec:
      imagePullSecrets:  # <-- Deve estar aqui, não dentro do container
      - name: acr-secret 
      containers:
      - name: regionalproducer
        image: techchallengeregistry.azurecr.io/regionalproducer:latest
        ports:
        - containerPort: 8080
  