apiVersion: apps/v1
kind: Deployment
metadata:
  name: regionalwriter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: regionalwriter
  template:
    metadata:
      labels:
        app: regionalwriter
    spec:
      imagePullSecrets: 
      - name: acr-secret 
      containers:
      - name: regionalwriter
        image: techchallengeregistry.azurecr.io/regionalwriter:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: regionalwriter
spec:
  selector:  
    app: regionalwriter
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http 
  type: ClusterIP
