apiVersion: apps/v1
kind: Deployment
metadata:
  name: regionalproducer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: regionalproducer
  template:
    metadata:
      labels:
        app: regionalproducer
    spec:
      imagePullSecrets: 
      - name: acr-secret 
      containers:
      - name: regionalproducer
        image: techchallengeregistry.azurecr.io/regionalproducer:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: regionalproducer
spec:
  selector:  
    app: regionalproducer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http 
  type: LoadBalancer