apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s # Intervalo de coleta de métricas

    scrape_configs:
    - job_name: 'regionalwriter'
      static_configs:
      - targets: ['regionalwriter-service:8080']

    - job_name: 'regionalproducer'
      static_configs:
      - targets: ['regionalproducer-service:8080']

    - job_name: 'regionaldata'
      static_configs:
      - targets: ['regionaldata-service:8080']

    - job_name: 'citydata'
      static_configs:
      - targets: ['citydata-service:8080']