apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app: prometheus
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090 
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus
        resources:
          requests:
            cpu: 250m  # Reduzido para 0.25 CPU
            memory: 512Mi  # Reduzido para 512Mi de RAM
          limits:
            cpu: 500m  # Limite máximo de 0.5 CPU
            memory: 750Mi  # Limite máximo de 750Mi de RAM
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-config
